// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exponentiation.proto

package services.exponentiation;

public final class ExponentiationProto {
  private ExponentiationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Exponentiation_ExponentiationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Exponentiation_ExponentiationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Exponentiation_ExponentiationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Exponentiation_ExponentiationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024exponentiation.proto\022\016Exponentiation\"\'" +
      "\n\025ExponentiationRequest\022\016\n\006number\030\001 \001(\005\"" +
      "&\n\026ExponentiationResponse\022\014\n\004next\030\001 \001(\0032" +
      "q\n\016Exponentiation\022_\n\014exponentiate\022%.Expo" +
      "nentiation.ExponentiationRequest\032&.Expon" +
      "entiation.ExponentiationResponse\"\000B0\n\027se" +
      "rvices.exponentiationB\023ExponentiationPro" +
      "toP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Exponentiation_ExponentiationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Exponentiation_ExponentiationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Exponentiation_ExponentiationRequest_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_Exponentiation_ExponentiationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Exponentiation_ExponentiationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Exponentiation_ExponentiationResponse_descriptor,
        new java.lang.String[] { "Next", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
