// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exponentiation.proto

package services.exponentiation;

public interface ExponentiationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Exponentiation.ExponentiationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   * @return The number.
   */
  int getNumber();
}
