// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exponentiation.proto

package services.exponentiation;

public interface ExponentiationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Exponentiation.ExponentiationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 next = 1;</code>
   * @return The next.
   */
  long getNext();
}
