// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: concatenation.proto

package services.concatenation;

/**
 * Protobuf type {@code Concatenation.ConcatenationRequest}
 */
public final class ConcatenationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Concatenation.ConcatenationRequest)
    ConcatenationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConcatenationRequest.newBuilder() to construct.
  private ConcatenationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConcatenationRequest() {
    textA_ = "";
    textB_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ConcatenationRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ConcatenationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            textA_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            textB_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return services.concatenation.ConcatenationProto.internal_static_Concatenation_ConcatenationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return services.concatenation.ConcatenationProto.internal_static_Concatenation_ConcatenationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            services.concatenation.ConcatenationRequest.class, services.concatenation.ConcatenationRequest.Builder.class);
  }

  public static final int TEXTA_FIELD_NUMBER = 1;
  private volatile java.lang.Object textA_;
  /**
   * <code>string textA = 1;</code>
   * @return The textA.
   */
  @java.lang.Override
  public java.lang.String getTextA() {
    java.lang.Object ref = textA_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      textA_ = s;
      return s;
    }
  }
  /**
   * <code>string textA = 1;</code>
   * @return The bytes for textA.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextABytes() {
    java.lang.Object ref = textA_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      textA_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEXTB_FIELD_NUMBER = 2;
  private volatile java.lang.Object textB_;
  /**
   * <code>string textB = 2;</code>
   * @return The textB.
   */
  @java.lang.Override
  public java.lang.String getTextB() {
    java.lang.Object ref = textB_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      textB_ = s;
      return s;
    }
  }
  /**
   * <code>string textB = 2;</code>
   * @return The bytes for textB.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBBytes() {
    java.lang.Object ref = textB_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      textB_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(textA_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, textA_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(textB_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, textB_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(textA_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, textA_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(textB_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, textB_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof services.concatenation.ConcatenationRequest)) {
      return super.equals(obj);
    }
    services.concatenation.ConcatenationRequest other = (services.concatenation.ConcatenationRequest) obj;

    if (!getTextA()
        .equals(other.getTextA())) return false;
    if (!getTextB()
        .equals(other.getTextB())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEXTA_FIELD_NUMBER;
    hash = (53 * hash) + getTextA().hashCode();
    hash = (37 * hash) + TEXTB_FIELD_NUMBER;
    hash = (53 * hash) + getTextB().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static services.concatenation.ConcatenationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static services.concatenation.ConcatenationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static services.concatenation.ConcatenationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static services.concatenation.ConcatenationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static services.concatenation.ConcatenationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static services.concatenation.ConcatenationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static services.concatenation.ConcatenationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static services.concatenation.ConcatenationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static services.concatenation.ConcatenationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static services.concatenation.ConcatenationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static services.concatenation.ConcatenationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static services.concatenation.ConcatenationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(services.concatenation.ConcatenationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Concatenation.ConcatenationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Concatenation.ConcatenationRequest)
      services.concatenation.ConcatenationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return services.concatenation.ConcatenationProto.internal_static_Concatenation_ConcatenationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return services.concatenation.ConcatenationProto.internal_static_Concatenation_ConcatenationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              services.concatenation.ConcatenationRequest.class, services.concatenation.ConcatenationRequest.Builder.class);
    }

    // Construct using services.concatenation.ConcatenationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      textA_ = "";

      textB_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return services.concatenation.ConcatenationProto.internal_static_Concatenation_ConcatenationRequest_descriptor;
    }

    @java.lang.Override
    public services.concatenation.ConcatenationRequest getDefaultInstanceForType() {
      return services.concatenation.ConcatenationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public services.concatenation.ConcatenationRequest build() {
      services.concatenation.ConcatenationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public services.concatenation.ConcatenationRequest buildPartial() {
      services.concatenation.ConcatenationRequest result = new services.concatenation.ConcatenationRequest(this);
      result.textA_ = textA_;
      result.textB_ = textB_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof services.concatenation.ConcatenationRequest) {
        return mergeFrom((services.concatenation.ConcatenationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(services.concatenation.ConcatenationRequest other) {
      if (other == services.concatenation.ConcatenationRequest.getDefaultInstance()) return this;
      if (!other.getTextA().isEmpty()) {
        textA_ = other.textA_;
        onChanged();
      }
      if (!other.getTextB().isEmpty()) {
        textB_ = other.textB_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      services.concatenation.ConcatenationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (services.concatenation.ConcatenationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object textA_ = "";
    /**
     * <code>string textA = 1;</code>
     * @return The textA.
     */
    public java.lang.String getTextA() {
      java.lang.Object ref = textA_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        textA_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string textA = 1;</code>
     * @return The bytes for textA.
     */
    public com.google.protobuf.ByteString
        getTextABytes() {
      java.lang.Object ref = textA_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        textA_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string textA = 1;</code>
     * @param value The textA to set.
     * @return This builder for chaining.
     */
    public Builder setTextA(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      textA_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string textA = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTextA() {
      
      textA_ = getDefaultInstance().getTextA();
      onChanged();
      return this;
    }
    /**
     * <code>string textA = 1;</code>
     * @param value The bytes for textA to set.
     * @return This builder for chaining.
     */
    public Builder setTextABytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      textA_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object textB_ = "";
    /**
     * <code>string textB = 2;</code>
     * @return The textB.
     */
    public java.lang.String getTextB() {
      java.lang.Object ref = textB_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        textB_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string textB = 2;</code>
     * @return The bytes for textB.
     */
    public com.google.protobuf.ByteString
        getTextBBytes() {
      java.lang.Object ref = textB_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        textB_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string textB = 2;</code>
     * @param value The textB to set.
     * @return This builder for chaining.
     */
    public Builder setTextB(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      textB_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string textB = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTextB() {
      
      textB_ = getDefaultInstance().getTextB();
      onChanged();
      return this;
    }
    /**
     * <code>string textB = 2;</code>
     * @param value The bytes for textB to set.
     * @return This builder for chaining.
     */
    public Builder setTextBBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      textB_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Concatenation.ConcatenationRequest)
  }

  // @@protoc_insertion_point(class_scope:Concatenation.ConcatenationRequest)
  private static final services.concatenation.ConcatenationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new services.concatenation.ConcatenationRequest();
  }

  public static services.concatenation.ConcatenationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConcatenationRequest>
      PARSER = new com.google.protobuf.AbstractParser<ConcatenationRequest>() {
    @java.lang.Override
    public ConcatenationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ConcatenationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ConcatenationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConcatenationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public services.concatenation.ConcatenationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

