// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: concatenation.proto

package services.concatenation;

public interface ConcatenationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Concatenation.ConcatenationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string textA = 1;</code>
   * @return The textA.
   */
  java.lang.String getTextA();
  /**
   * <code>string textA = 1;</code>
   * @return The bytes for textA.
   */
  com.google.protobuf.ByteString
      getTextABytes();

  /**
   * <code>string textB = 2;</code>
   * @return The textB.
   */
  java.lang.String getTextB();
  /**
   * <code>string textB = 2;</code>
   * @return The bytes for textB.
   */
  com.google.protobuf.ByteString
      getTextBBytes();
}
