// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: concatenation.proto

package services.concatenation;

public interface ConcatenationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Concatenation.ConcatenationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string concatenatedText = 1;</code>
   * @return The concatenatedText.
   */
  java.lang.String getConcatenatedText();
  /**
   * <code>string concatenatedText = 1;</code>
   * @return The bytes for concatenatedText.
   */
  com.google.protobuf.ByteString
      getConcatenatedTextBytes();
}
