// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: concatenation.proto

package services.concatenation;

public final class ConcatenationProto {
  private ConcatenationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Concatenation_ConcatenationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Concatenation_ConcatenationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Concatenation_ConcatenationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Concatenation_ConcatenationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023concatenation.proto\022\rConcatenation\"4\n\024" +
      "ConcatenationRequest\022\r\n\005textA\030\001 \001(\t\022\r\n\005t" +
      "extB\030\002 \001(\t\"1\n\025ConcatenationResponse\022\030\n\020c" +
      "oncatenatedText\030\001 \001(\t2k\n\rConcatenation\022Z" +
      "\n\013concatenate\022#.Concatenation.Concatenat" +
      "ionRequest\032$.Concatenation.Concatenation" +
      "Response\"\000B.\n\026services.concatenationB\022Co" +
      "ncatenationProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Concatenation_ConcatenationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Concatenation_ConcatenationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Concatenation_ConcatenationRequest_descriptor,
        new java.lang.String[] { "TextA", "TextB", });
    internal_static_Concatenation_ConcatenationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Concatenation_ConcatenationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Concatenation_ConcatenationResponse_descriptor,
        new java.lang.String[] { "ConcatenatedText", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
