// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: isPrime.proto

package services.primality;

public interface IsPrimeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Primality.IsPrimeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   * @return The number.
   */
  int getNumber();
}
