// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: isPrime.proto

package services.primality;

public interface IsPrimeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Primality.IsPrimeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isPrime = 1;</code>
   * @return The isPrime.
   */
  boolean getIsPrime();
}
